<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
	<td>${tempBean.id}</td>
		<td>
		${tempBean.name}
		</td>
		<td>
		${tempBean.address}
		</td>
		<td>
		${tempBean.contact}
		</td>
		<td>
		${tempBean.tel}
		</td>
		<td>
		${tempBean.registMoney}
		</td>
		<td>
		${tempBean.industry}
		</td>
		<td>
		${tempBean.bandNum}
		</td>
		<td>
		${tempBean.remark}
		</td>